---
global_config:
  environment_name: |CLUSTER_NAME|
  cloud_platform: aws
  aws_region: |AWS_REGION|
  env_id: |CLUSTER_NAME|
  confirm_destroy: False

nfs_server:
- name: "{{ env_id }}-elastic"
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.12.28
  compute_flavour: |COMPUTE_INSTANCE_TYPE|
  compute_nodes: |COMPUTE_INSTANCE_NODE_COUNT|
  infrastructure:
    type: rosa
    aws_region: "{{ aws_region }}"
    multi_zone: |MULTI_ZONE|
    use_sts: True
    subnet_ids:
    - |PRIVATE_SUBNET_1|
    - |PRIVATE_SUBNET_2|
    - |PRIVATE_SUBNET_3|
    - |PUBLIC_SUBNET_1|
    - |PUBLIC_SUBNET_2|
    - |PUBLIC_SUBNET_3|
  openshift_storage:
  - storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic