---
global_config:
  environment_name: |CLUSTER_NAME|
  cloud_platform: aws
  aws_region: |AWS_REGION|
  env_id: |CLUSTER_NAME|
  confirm_destroy: False

nfs_server:
- name: "{{ env_id }}-elastic"
  infrastructure:
    aws_region: "{{ aws_region }}"

openshift:
- name: "{{ env_id }}"
  ocp_version: |OPENSHIFT_VERSION|
  compute_flavour: |COMPUTE_INSTANCE_TYPE|
  compute_nodes: |COMPUTE_INSTANCE_NODE_COUNT|
  infrastructure:
    type: rosa
    aws_region: "{{ aws_region }}"
    multi_zone: False
    use_sts: False
    subnet_ids:
    - |PRIVATE_SUBNET_1|
    - |PUBLIC_SUBNET_1|
  mcg:
    install: True
    storage_type: storage-class
    storage_class: gp3-csi
  openshift_storage:
  - storage_name: "{{ env_id }}-elastic"
    storage_type: aws-elastic