AWSTemplateFormatVersion: '2010-09-09'
Description: Immersion day API gateway and lambda template.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: KeyPair Configuration
        Parameters:
          - KeyPairName
Parameters:
  KeyPairName:
    Default: "immersionday-cluster"
    Description: Custom cluster name for kubernetes.io/cluster/tags.
    Type: String
    AllowedPattern: ^[0-9a-z-]*$
Resources:
  KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Join 
          - ""
          - - !Ref KeyPairName
      Tags:
        - Key: Name
          Value: !Ref KeyPairName
  S3BucketForLogs:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: 
        Status: "Suspended"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  KeyPairName:
    Description: SSH keypair name
    Value: !Ref KeyPair
  S3BucketForLogs:
    Description: The name of the S3 bucket where IBM Cloud Pak for Data deployment logs are to be exported
    Value: !Ref S3BucketForLogs

