AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket template.
Parameters:
  Versioning:
    Description: Whether Versioning is required for S3 bucket
    Type: String
    Default: Suspended
    AllowedValues: [Suspended, Enabled]
  Owner:
    Description: S3 bucket Owner
    Type: String
    Default: IBMImmerssionday
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
#      BucketName: !Ref BucketName
      VersioningConfiguration: 
        Status: !Ref Versioning
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "Owner"
          Value: !Ref Owner
  S3IAMUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      Policies:
        - PolicyName: !Join
            - '-'
            - - S3BucketUserPermissions
              - !Ref 'S3Bucket'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt 'S3Bucket.Arn'
                  - !Join
                    - ''
                    - - !GetAtt 'S3Bucket.Arn'
                      - /*
  S3IAMUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref S3IAMUser
  S3CredentialSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "S3ImmerssiondayBucketSecrets"
      SecretString: !Sub 
        - '{"aws_secret_access_key":"${S3IAMUserAccessKey}", "aws_access_key_id":"${S3IAMUserSecret}"}'
        - {S3IAMUserAccessKey: !Ref S3IAMUserAccessKey, S3IAMUserSecret: !GetAtt S3IAMUserAccessKey.SecretAccessKey}
Outputs:
  BucketName:
    Value: !Ref S3Bucket
  BucketArn:
    Value: !GetAtt S3Bucket.Arn
  S3CredentialSecret:
    Value: !Ref S3CredentialSecret
  
      