AWSTemplateFormatVersion: '2010-09-09'
Description: 'test SSM reference'
Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "test"
      Description: SSM Parameter for running date command.
Outputs:
  SSMVAR:
    Description: test value reference
    Value: !Sub "{{resolve:ssm:${BasicParameter}}}"
