AWSTemplateFormatVersion: '2010-09-09'
Description: Immersion day IAM admin users created by the template.
Resources:
  AdminIAMUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      Policies:
        - PolicyName: !Join
            - '-'
            - - ImmersionDayAdminUser
              - !Select [2, !Split ['/', !Ref AWS::StackId]]      
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  AdminAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref AdminIAMUser
  AdminUserCredentialSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "AdminUserCredentialSecret"
      SecretString: !Sub 
        - '{"admin_user_secret_access_key":"${AdminAccessKey}", "admin_user_access_key_id":"${AdminSecretKey}"}'
        - {AdminAccessKey: !Ref AdminAccessKey, AdminSecretKey: !GetAtt AdminAccessKey.SecretAccessKey}
Outputs:
  AdminUserAccessKey:
    Value: !Ref AdminAccessKey
  AdminIAMUser:
    Value: !Ref AdminIAMUser
  AdminUserCredentialSecret:
    Value: !Ref AdminUserCredentialSecret